---
apiVersion: batch/v1
kind: Job
metadata:
  name: etcd-empty-dir-cleanup
  namespace: kube-system
spec:
  template:
    spec:
      hostNetwork: true
      restartPolicy: OnFailure
      containers:
      - name: k8s-cleanup
        image: onfido/k8s-cleanup
        command: ["/bin/bash", "/bin/etcd-empty-dir-cleanup.sh"]
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
