---
apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-cleanup
  namespace: kube-system
spec:
  template:
    spec:
      # nodeSelector:
      #   kubernetes.io/role: master
      # tolerations:
      # - effect: NoSchedule
      #   key: node-role.kubernetes.io/master
      restartPolicy: OnFailure
      containers:
        - name: k8s-cleanup
          image: onfido/k8s-cleanup
          command: ["/bin/bash", "/bin/k8s-clean.sh"]
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
